### ISSUE TITLE
代码内部变量不一致问题

### ISSUE THREAD

**Issue by LostRaccoon** [qunat/Pythonocc-CAD#4]
读取Ribbon_sketcher.ini但是文件是RibbonSketcher.ini
	def uptoplane(self):
		self.parent.InteractiveOperate.InteractiveModule="SKETCH"
		self.parent.Displayshape_core.canva._display.register_select_callback(self.clicked_callback)

Displayshape_core.不存在，应该为Displayshape_core_dict

**Comment by qunat** [comment]
草绘暂时不能用了 我整个架构都改了 不好意思



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月15日(周三) 下午4:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qunat/Pythonocc-CAD] 代码内部变量不一致问题 (Issue #4)




 
读取Ribbon_sketcher.ini但是文件是RibbonSketcher.ini
 def uptoplane(self):
 self.parent.InteractiveOperate.InteractiveModule="SKETCH"
 self.parent.Displayshape_core.canva._display.register_select_callback(self.clicked_callback)
 
Displayshape_core.不存在，应该为Displayshape_core_dict

**Comment by LostRaccoon** [comment]
嗯嗯，加油
